name: Python Unit Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up the Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Install dependencies if requirements.txt is present
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f "requirements.txt" ]; then pip install -r requirements.txt; fi
      - uses: nanasess/setup-chromedriver@v2
        with:
        # Optional: do not specify to match Chrome's version
          chromedriver-version: '88.0.4324.96'
        # Optional: if your chrome binary name is different
          chromeapp: chrome
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
      # Run the unit tests with unittest
      - name: Run Selenium Tests
        env:
          DISPLAY: ":99"  # Required for the Xvfb virtual display
        working-directory: selenium_python
        run: |
          python -m unittest discover -s tests
